#!/usr/bin/env ansible-playbook

################################################################################
#
# Title:        42_create_s3_user.yml
# Date:         2023-11-08
# Description:  Create an S3 user
#               with Ansible module
#
# Modules:      na_ontap_s3_users
#
# URLs:         http://docs.netapp.com/ontap-9/index.jsp
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.na_ontap_s3_users
#
################################################################################

- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname:         "{{ PRI_CLU }}"
      username:         "{{ PRI_CLU_USER }}"
      password:         "{{ PRI_CLU_PASS }}"
      https:            true
      validate_certs:   false
      use_rest:         Always
  vars_files:
    - global_nas.vars
  collections:
    - netapp.ontap

  tasks:
  - name: Create an s3 user
    na_ontap_s3_users:
      state:            present
      name:             "s3_user"
      vserver:          "{{ PRI_SVM }}"
      comment:          Created with Ansible
      <<: *input
    register: result

  - name: print variables
    ansible.builtin.debug:
      msg: Access Key {{ result.access_key }} and Secret Key {{ result.secret_key }}

  - name: Check the result
    assert:
      that:
        - result.access_key
        - result.secret_key
