#!/usr/bin/env ansible-playbook

################################################################################
#
# Title:        43_create_s3_group.yml
# Author:       Vish Hulikal
# Date:         2023-10-25
# Description:  Create a S3 group
#               with Ansible module
#
# Modules:      na_ontap_s3_groups
#
# URLs:         http://docs.netapp.com/ontap-9/index.jsp
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.na_ontap_s3_groups
#
################################################################################

- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname:         "{{ PRI_CLU }}"
      username:         "{{ PRI_CLU_USER }}"
      password:         "{{ PRI_CLU_PASS }}"
      https:            true
      validate_certs:   false
      use_rest:         Always
  vars_files:
    - global_nas.vars
  collections:
    - netapp.ontap

  tasks:
  - name: Create a S3 Group
    na_ontap_s3_groups:
      state:            present
      name:             "{{ S3_Group }}"
      vserver:          "{{ PRI_SVM }}"
      users:
        - name:         "{{ S3_User }}"
      policies:
        - name:         FullAccess
      comment:          Created with Ansible
      <<: *input


