#!/usr/bin/env ansible-playbook

################################################################################
#
# Title:        45_create_s3_bucket.yml
# Author:       Vish Hulikal
# Date:         2023-09-14
# Description:  Create a S3 bucket
#               with Ansible module
#
# Modules:      na_ontap_svm
#
# URLs:         http://docs.netapp.com/ontap-9/index.jsp
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.na_ontap_s3_buckets
#
################################################################################

- hosts: localhost
  gather_facts: false
  vars:
    input: &variables
      hostname:         "{{ PRI_CLU }}"
      username:         "{{ PRI_CLU_USER }}"
      password:         "{{ PRI_CLU_PASS }}"
      https:            true
      validate_certs:   false
      use_rest:         Always
  vars_files:
    - global_nas.vars
  collections:
    - netapp.ontap

  tasks:
  - name: Create a S3 bucket
    na_ontap_s3_buckets:
      state:            present
      name:             "s3-container"
      vserver:          "{{ PRI_SVM }}"
      aggregates:       "{{ PRI_AGGR }}"
      size:             102005473280
      comment:          "Container for S3 objects"
      <<: *variables


