#!/usr/bin/env ansible-playbook

################################################################################
#
# Title:        cleanup_all.yml
# Description:  Clean up the entire environment
#               with Ansible modules
#
# Authors:      Ron Fiest and Vish Hulikal
# Date:         11-06-2023
# Modules:      na_ontap_rest_info
#               na_ontap_volume
#               na_ontap_cifs_server
#               na_ontap_svm
#
# URLs:         http://docs.netapp.com/ontap-9/index.jsp
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.na_ontap_rest_info
# ansible-doc netapp.ontap.na_ontap_volume
# ansible-doc netapp.ontap.na_cifs_server
# ansible-doc netapp.ontap.na_ontap_svm
#
################################################################################

- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname:       "{{ PRI_CLU }}"
      username:       "{{ PRI_CLU_USER }}"
      password:       "{{ PRI_CLU_PASS }}"
      https: true
      validate_certs: false
      use_rest: Always
  vars_files:
    - global.vars
  collections:
    - netapp.ontap

  tasks:

    - name: Get Ontap Rest Info
      na_ontap_rest_info:
        state:
        <<: *input
      register: netapp

    - name: Get Ontap Info
      na_ontap_info:
        state:
        <<: *input
      register: netapp1

    - name: Unmap LUN
      na_ontap_lun_map:
        state: absent
        initiator_group_name: "{{ IGROUP_NAME }}"
        path: "/vol/{{ VOL_NAME }}/{{ LUN_NAME }}"
        https: true
        vserver: "{{ PRI_SVM }}"
        hostname: "{{ PRI_CLU }}"
        username: "{{ PRI_CLU_USER }}"
        password: "{{ PRI_CLU_PASS }}"
        validate_certs: false
        <<: *input
      with_items:
        "{{ luns }}"
      when: luns != None

    - name: Delete interface
      na_ontap_interface:
        state: absent
        interface_name: "{{ PRI_SVM }}_iscsi_01"
        vserver: "{{ PRI_SVM }}"
        <<: *input

    - name: Delete interface
      na_ontap_interface:
        state: absent
        interface_name: "{{ PRI_SVM }}_iscsi_02"
        vserver: "{{ PRI_SVM }}"
        <<: *input

    - name: Stop and Disable iSCSI
      na_ontap_iscsi:
        state:                 absent
        vserver:               "{{ PRI_SVM }}"
        service_state:         stopped
        <<: *input

    - name: Delete the LUN
      na_ontap_lun:
        state: absent
        name: "{{ LUN_NAME }}"
        flexvol_name: "{{ VOL_NAME }}"
        vserver: "{{ PRI_SVM }}"
        size: "{{ LUN_SIZE }}"
        size_unit: gb
        ostype: windows
        space_reserve: false
        <<: *input
      with_items:
        "{{ luns }}"
      when: luns != None

    - name: Delete the iGroup
      na_ontap_igroup:
        state: absent
        name: "{{ IGROUP_NAME }}"
        vserver: "{{ PRI_SVM }}"
        initiator_group_type: iscsi
        ostype: windows
        initiator: "{{ WIN_IQN }}"
        <<: *input
      with_items:
        "{{ igroups }}"
      when: igroups != None

    - name: Delete the FlexVols
      na_ontap_volume:
        state:           absent
        vserver:         "{{ PRI_SVM }}"
        name:            "{{ netapp1.ontap_info.volume_info[item].volume_id_attributes.name }}"
        <<: *input
      with_items:
        "{{ netapp1.ontap_info.volume_info }}"
      when:
      - netapp1.ontap_info.volume_info[item].volume_id_attributes.owning_vserver_name == PRI_SVM
      - netapp1.ontap_info.volume_info[item].volume_id_attributes.name is not regex(".*_root")

    - name: Delete CIFS server on primary SVM
      na_ontap_cifs_server:
        state:                 absent
        name:                  "{{ PRI_SVM }}"
        vserver:               "{{ PRI_SVM }}"
        domain:                "{{ PRI_AD_DOMAIN }}"
        admin_user_name:       "{{ PRI_AD_USER }}"
        admin_password:        "{{ PRI_AD_PASS }}"
        <<: *input
      with_items:
        "{{ netapp.ontap_info.vserver_info }}"
      when:
        - netapp.ontap_info.vserver_info[PRI_SVM] is defined

    - name: Delete the SVM
      na_ontap_svm:
        state:                 absent
        name:                  "{{ PRI_SVM }}"
        <<: *input
