#!/usr/bin/env ansible-playbook

################################################################################
#
# Title:        create_iscsi_lifs.yml
# Author:       Ronald Feist	
# Date:         2020-06-09
# Description:  Create iSCSI interfaces for the primary SVM
#               with Ansible modules
#
# Modules:      na_ontap_interface
#
# URLs:         http://docs.netapp.com/ontap-9/index.jsp
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.na_ontap_interface
#
################################################################################

- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname:       "{{ PRI_CLU }}"
      username:       "{{ PRI_CLU_USER }}"
      password:       "{{ PRI_CLU_PASS }}"
      https:          true
      validate_certs: false
      use_rest:       Always
  vars_files:
    - global.yml
  collections:
    - netapp.ontap

  tasks:
  - name: Create iSCSI interface for node01
    na_ontap_interface:
      state:                 present
      interface_name:        "{{ PRI_SVM }}_iscsi_01"
      vserver:               "{{ PRI_SVM }}"
      address:               "{{ PRI_ISCSI_IP }}"
      netmask:               "{{ PRI_SVM_NETMASK }}"
      home_node:             "{{ PRI_CLU_NODE1 }}"
      home_port:             "{{ PRI_DATA_PORT }}"
      protocols:             iscsi
      <<: *input
      firewall_policy:       data
      role:                  data
  - name: Create iSCSI interfaces for node02
    na_ontap_interface:
      state:                 present
      interface_name:        "{{ PRI_SVM }}_iscsi_02"
      vserver:               "{{ PRI_SVM }}"
      address:               "{{ SEC_ISCSI_IP }}"
      netmask:               "{{ PRI_SVM_NETMASK }}"
      home_node:             "{{ PRI_CLU_NODE2 }}"
      home_port:             "{{ PRI_DATA_PORT }}"
      protocols:             iscsi
      <<: *input
      firewall_policy:       data
      role:                  data