#!/usr/bin/env ansible-playbook

################################################################################
#
# Title:        disable_iscsi.yml
# Author:       Ronald Feist
# Date:         2020-06-09
# Description:  Enable iSCSI on primary SVM
#               with Ansible modules
#
# Modules:      na_ontap_iscsi
#
# URLs:         http://docs.netapp.com/ontap-9/index.jsp
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.na_ontap_iscsi
#
################################################################################

- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname:       "{{ PRI_CLU }}"
      username:       "{{ PRI_CLU_USER }}"
      password:       "{{ PRI_CLU_PASS }}"
      https:          true
      validate_certs: false
      use_rest:       Always
  vars_files:
    - global.vars
  collections:
    - netapp.ontap

  tasks:
  - name: Disable iSCSI on primary SVM
    na_ontap_iscsi:
      state:                 absent
      vserver:               "{{ PRI_SVM }}"
      service_state:         stopped
      <<: *input