#!/usr/bin/env ansible-playbook

################################################################################
#
# Title:        get_lun_info_cluster1.yml
# Author:       Ronald Feist
# Date:         2020-06-10
# Description:  Create a volume on the aggregate with the most headroom
#               with Ansible modules
#
# Modules:      na_ontap_info
#
# URLs:         http://docs.netapp.com/ontap-9/index.jsp
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.na_ontap_volume
#
################################################################################

- hosts: localhost
  name: Get ONTAP LUN Information
  vars:
    input: &input
      hostname:       "{{ PRI_CLU }}"
      username:       "{{ PRI_CLU_USER }}"
      password:       "{{ PRI_CLU_PASS }}"
      https:          true
      validate_certs: false
      use_rest:       Always
  vars_files:
    - global.vars
  collections:
    - netapp.ontap
  tasks:
  - name: gather info
    na_ontap_info:
      state: info
      <<: *input
      gather_subset:
      - lun_info
      - igroup_info
    register: ontap_info
  - debug:
     msg: "{{ ontap_info.ontap_info }}"
